# Generated by Django 4.0.6 on 2022-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'tack'), name='unique_user_for_tack'),
        ),
    ]
