# Generated by Django 4.1 on 2022-08-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DwollaEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("topic", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField()),
                ("_links", models.JSONField()),
                ("account", models.JSONField()),
                ("resource", models.JSONField()),
                ("customer", models.JSONField()),
                ("created", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Dwolla event",
                "verbose_name_plural": "Dwolla events",
                "db_table": "dwolla_events",
            },
        ),
    ]
