# Generated by Django 4.1 on 2022-08-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dwolla_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dwollaevent",
            old_name="_links",
            new_name="self_res",
        ),
    ]
