# Generated by Django 4.0.7 on 2022-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwolla_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwollaRemovedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwolla_id', models.UUIDField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dwolla removed account',
                'verbose_name_plural': 'Dwolla removed accounts',
                'db_table': 'dwolla_removed_accounts',
            },
        ),
    ]
