# Generated by Django 4.1 on 2022-08-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dwolla_service", "0002_rename__links_dwollaevent_self_res"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dwollaevent",
            name="account",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dwollaevent",
            name="customer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dwollaevent",
            name="resource",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dwollaevent",
            name="self_res",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
