version: '3.8'

services:
  web:
    container_name: 'web'
    build: .
    restart: always
    entrypoint: ["/app/docker-entrypoint.sh"]
    volumes:
      - .:/app/
    env_file:
      - tackapp/dev.env
    command: ["daphne", "-b", "0.0.0.0", "-p", "8020", "tackapp.asgi:application"]
#    command: ["python3", "manage.py", "runserver"]
    ports:
      - "8020:8020"
    depends_on:
      - postgres

  celery:
    build: .
    container_name: 'celery'
    restart: always
    command: celery -A tackapp worker --loglevel=info --logfile=celery.log
    env_file:
      - tackapp/dev.env
    depends_on:
      - web
      - redis

  redis:
    container_name: 'redis'
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  rabbit:
    container_name: 'rabbit'
    image: rabbitmq:3.10-management
    restart: always
    env_file:
      - tackapp/dev.env
    ports:
      - "15672:15672"

  postgres:
    image: postgres:14.4-alpine
    container_name: 'postgres'
    restart: always
    volumes:
      - ./database:/var/lib/postgresql
    env_file:
      - tackapp/dev.env
    ports:
      - "5432:5432"

  flower:
    build: .
    container_name: 'flower'
    restart: always
    command: celery -A tackapp --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - tackapp/dev.env
    depends_on:
      - web
      - redis
      - celery
