version: '3.8'

services:
  web:
    container_name: 'web'
    build: .
    restart: always
    entrypoint: ["/app/docker-entrypoint.sh"]
    volumes:
      - .:/app/
    command: python3 manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4-alpine
    container_name: 'postgres'
    restart: always
    env_file:
      - tackapp/.env
    ports:
      - "5432:5432"
