version: '3.8'

services:
  web:
    container_name: 'web'
    build: .
    restart: always
    entrypoint: ["/app/docker-entrypoint.sh"]
    volumes:
      - .:/app/
    command: python3 manage.py runsslserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4-alpine
    container_name: 'postgres'
    restart: always
    env_file:
      - tackapp/.env
    ports:
      - "5432:5432"

  swagger:
    image: swaggerapi/swagger-editor
    working_dir: /api
    volumes:
      - ./:/api
    ports:
      - "7777:8080"
    environment:
      - SWAGGER_FILE=/api/swagger.yaml
