# Generated by Django 4.0.7 on 2022-09-12 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djstripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='djstripe_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='application_fee',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_for_charge', to='djstripe.applicationfee', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='balance_transaction',
            field=djstripe.fields.StripeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.balancetransaction', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='customer',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='djstripe.customer', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='dispute',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='djstripe.dispute', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='invoice',
            field=djstripe.fields.StripeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='djstripe.invoice', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='on_behalf_of',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='payment_intent',
            field=djstripe.fields.StripeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='djstripe.paymentintent', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='payment_method',
            field=djstripe.fields.StripeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='djstripe.paymentmethod', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='source',
            field=djstripe.fields.PaymentMethodForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='djstripe.djstripepaymentmethod'),
        ),
        migrations.AddField(
            model_name='charge',
            name='source_transfer',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='djstripe.transfer', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='charge',
            name='transfer',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.transfer', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=djstripe.fields.StripeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_cards', to='djstripe.customer', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='card',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='customer',
            field=djstripe.fields.StripeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account', to='djstripe.customer', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='applicationfeerefund',
            name='balance_transaction',
            field=djstripe.fields.StripeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.balancetransaction', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='applicationfeerefund',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='applicationfeerefund',
            name='fee',
            field=djstripe.fields.StripeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='djstripe.applicationfee', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='account',
            field=djstripe.fields.StripeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_fees', to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='balance_transaction',
            field=djstripe.fields.StripeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.balancetransaction', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='charge',
            field=djstripe.fields.StripeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.charge', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='applicationfee',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AddField(
            model_name='apikey',
            name='djstripe_owner_account',
            field=djstripe.fields.StripeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
        migrations.AlterUniqueTogether(
            name='djstripeupcominginvoicetotaltaxamount',
            unique_together={('invoice', 'tax_rate')},
        ),
        migrations.AlterUniqueTogether(
            name='djstripeinvoicetotaltaxamount',
            unique_together={('invoice', 'tax_rate')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('subscriber', 'livemode', 'djstripe_owner_account')},
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('id', 'livemode')},
        ),
    ]
