# Generated by Django 4.1 on 2022-08-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tacks_rating",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
    ]
