# Generated by Django 4.0.7 on 2022-09-14 08:30

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=user.models.LowercaseEmailField(default=None, max_length=254, null=True, unique=True),
        ),
    ]
