# Generated by Django 4.0.6 on 2022-07-26 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.DecimalValidator(8, 2), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999.99)])),
                ('offer_type', models.CharField(choices=[('offer', 'Offer'), ('counter_offer', 'Counter Offer')], default='offer', max_length=13)),
                ('is_accepted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('lifetime_seconds', models.PositiveIntegerField(default=900)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Tack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.DecimalValidator(8, 2), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999.99)])),
                ('description', models.CharField(max_length=512)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField()),
                ('allow_counter_offer', models.BooleanField()),
                ('status', models.CharField(choices=[('created', 'Just created'), ('active', 'Tack have active Offers'), ('accepted', 'Offer accepted'), ('in_progress', 'In progress'), ('waiting_review', 'Waiting for Review'), ('finished', 'Finished')], default='created', max_length=16)),
                ('completion_message', models.CharField(blank=True, max_length=256, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('estimation_time_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tack',
                'verbose_name_plural': 'Tacks',
                'db_table': 'tacks',
            },
        ),
    ]
