# Generated by Django 4.0.7 on 2022-09-12 16:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('offer_type', models.CharField(choices=[('offer', 'Offer'), ('counter_offer', 'Counter Offer')], default='offer', max_length=13)),
                ('is_accepted', models.BooleanField(default=False)),
                ('lifetime_seconds', models.PositiveIntegerField(default=900)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='PopularTack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('groups', 'Groups type'), ('friends', 'Friends type'), ('public', 'Public (Anonymous)')], default='groups', max_length=7)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('description', models.CharField(max_length=512)),
                ('allow_counter_offer', models.BooleanField()),
                ('estimation_time_seconds', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Popular Tack',
                'verbose_name_plural': 'Popular Tacks',
                'db_table': 'popular_tacks',
            },
        ),
        migrations.CreateModel(
            name='Tack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('groups', 'Groups type'), ('friends', 'Friends type'), ('public', 'Public (Anonymous)')], default='groups', max_length=7)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('description', models.CharField(max_length=512)),
                ('allow_counter_offer', models.BooleanField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('waiting_review', 'Waiting Review'), ('finished', 'Finished')], default='created', max_length=16)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('estimation_time_seconds', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('accepted_time', models.DateTimeField(blank=True, null=True)),
                ('completion_message', models.CharField(blank=True, max_length=256, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_offer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tack_accepted_offer', to='tack.offer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'verbose_name': 'Tack',
                'verbose_name_plural': 'Tacks',
                'db_table': 'tacks',
            },
        ),
    ]
