# Generated by Django 4.0.7 on 2022-09-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tack', '0001_initial'),
        ('tack_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tack',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tack_group.group'),
        ),
    ]
