# Generated by Django 4.1 on 2022-08-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tack", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tack",
            name="accepted_offer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tack_accepted_offer",
                to="tack.offer",
            ),
        ),
    ]
