# Generated by Django 4.0.6 on 2022-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
