# Generated by Django 4.0.6 on 2022-07-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0003_offer_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='tack',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
