# Generated by Django 4.1 on 2022-08-23 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tack", "0003_tack_accepted_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tack",
            name="runner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tack_runner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
