# Generated by Django 4.0.7 on 2022-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0003_offer_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('deleted', 'Deleted'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='created', max_length=12),
        ),
    ]
