# Generated by Django 4.0.7 on 2022-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0004_remove_offer_is_accepted_remove_offer_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('deleted', 'Deleted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='created', max_length=12),
        ),
    ]
