# Generated by Django 4.1 on 2022-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tack", "0005_tack_is_canceled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tack",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("active", "Active"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In progress"),
                    ("waiting_review", "Waiting Review"),
                    ("finished", "Finished"),
                ],
                default="created",
                max_length=16,
            ),
        ),
    ]
