# Generated by Django 4.0.6 on 2022-07-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0005_tack_group_alter_offer_price_alter_tack_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tack',
            name='expiration_time',
        ),
    ]
