# Generated by Django 4.0.7 on 2022-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0007_alter_offer_runner_alter_tack_tacker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tack',
            name='start_completion_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
