# Generated by Django 4.0.6 on 2022-08-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0008_tack_group_alter_offer_price_alter_tack_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tack',
            name='type',
            field=models.CharField(choices=[('groups', 'Groups type'), ('friends', 'Friends type'), ('public', 'Public (Anonymous)')], default='groups', max_length=7),
        ),
    ]
