# Generated by Django 4.0.8 on 2022-10-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0008_tack_start_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='populartack',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tack',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
    ]
