# Generated by Django 4.0.6 on 2022-08-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0010_alter_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTacks',
            fields=[
                ('tack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tack.tack')),
            ],
            bases=('tack.tack',),
        ),
    ]
