# Generated by Django 4.0.6 on 2022-08-03 09:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_groupmutes'),
        ('tack', '0011_populartacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('groups', 'Groups type'), ('friends', 'Friends type'), ('public', 'Public (Anonymous)')], default='groups', max_length=7)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('description', models.CharField(max_length=512)),
                ('allow_counter_offer', models.BooleanField()),
                ('estimation_time_seconds', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group')),
                ('tacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Popular Tack',
                'verbose_name_plural': 'Popular Tacks',
                'db_table': 'popular_tacks',
            },
        ),
        migrations.DeleteModel(
            name='PopularTacks',
        ),
    ]
