# Generated by Django 4.1 on 2022-08-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tack", "0013_alter_populartack_tacker_alter_tack_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="tack",
            name="accepted_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
