# Generated by Django 4.1 on 2022-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tack", "0014_tack_accepted_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tack",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
