# Generated by Django 4.0.7 on 2022-08-08 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0016_remove_offer_creation_time_tack_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
