# Generated by Django 4.0.6 on 2022-07-26 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.DecimalValidator(8, 2), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999.99)])),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_account',
            },
        ),
    ]
