# Generated by Django 4.0.7 on 2022-09-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_dwolla',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_stripe',
        ),
        migrations.AddField(
            model_name='transaction',
            name='action_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_name',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('dwolla', 'Dwolla')], default='stripe', max_length=10),
            preserve_default=False,
        ),
    ]
