# Generated by Django 4.0.7 on 2022-09-05 07:53

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_percent', models.DecimalField(decimal_places=2, default=2.9, max_digits=4, validators=[core.validators.percent_validator])),
                ('stripe_const_sum', models.PositiveIntegerField(default=30)),
                ('dwolla_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=4, validators=[core.validators.percent_validator])),
                ('dwolla_const_sum', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.PositiveIntegerField()),
                ('amount_with_fees', models.PositiveIntegerField()),
                ('service_fee', models.PositiveIntegerField()),
                ('is_dwolla', models.BooleanField(default=False)),
                ('is_stripe', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('is_succeeded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
