# Generated by Django 4.0.6 on 2022-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='stripe_user',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
