# Generated by Django 4.0.7 on 2022-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='dwolla_user',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
