# Generated by Django 4.0.6 on 2022-07-28 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_bankaccount_stripe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='stripe_user',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='usd_balance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
