# Generated by Django 4.0.7 on 2022-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_userpaymentmethods_plaid_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='stripe_user',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
