# Generated by Django 4.1 on 2022-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_bankaccount_dwolla_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpaymentmethods",
            old_name="payment_method",
            new_name="dwolla_payment_method",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="dwolla_access_token",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
