# Generated by Django 4.0.7 on 2022-09-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_fee_fee_max_remove_fee_fee_min_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DwollaRemovedAccount',
        ),
    ]
