# Generated by Django 4.0.7 on 2022-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_bankaccount_stripe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_difference',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
