# Generated by Django 4.1 on 2022-08-26 09:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0004_rename_payment_method_userpaymentmethods_dwolla_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        max_digits=4,
                        validators=[core.validators.percent_validator],
                    ),
                ),
                ("fee_min", models.PositiveIntegerField(default=25)),
                ("fee_max", models.PositiveIntegerField(default=1500)),
            ],
            options={
                "verbose_name": "Fee",
                "verbose_name_plural": "Fees",
                "db_table": "fees",
            },
        ),
    ]
