# Generated by Django 4.1 on 2022-08-28 13:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="dwolla_access_token",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="fee",
            name="fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=3.0,
                max_digits=4,
                validators=[core.validators.percent_validator],
            ),
        ),
    ]
