# Generated by Django 4.0.7 on 2022-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_transaction_fee_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee_difference',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
