# Generated by Django 4.1 on 2022-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_bankaccount_dwolla_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DwollaRemovedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dwolla_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "Dwolla removed account",
                "verbose_name_plural": "Dwolla removed accounts",
                "db_table": "dwolla_removed_accounts",
            },
        ),
        migrations.AddField(
            model_name="userpaymentmethods",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="userpaymentmethods",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("bank_account",),
                name="bank_account_one_primary",
            ),
        ),
    ]
