# Generated by Django 4.0.7 on 2022-10-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_transaction_fee_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service_name',
            field=models.CharField(choices=[('stripe', 'Stripe (Card)'), ('d_wallet', 'Stripe (Digital Wallet)'), ('dwolla', 'Dwolla (Bank Account)')], max_length=10),
        ),
    ]
