# Generated by Django 4.0.6 on 2022-08-01 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_bankaccount_usd_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='stripe_user',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserPaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=64)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.bankaccount')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
                'db_table': 'payments',
            },
        ),
    ]
