# Generated by Django 4.1 on 2022-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_dwollaremovedaccount_userpaymentmethods_is_primary_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userpaymentmethods",
            name="bank_account_one_primary",
        ),
        migrations.AddConstraint(
            model_name="userpaymentmethods",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("bank_account",),
                name="bank_account_one_primary",
            ),
        ),
    ]
