# Generated by Django 4.0.8 on 2022-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transaction_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
