# Generated by Django 4.0.6 on 2022-07-22 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tack', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invitation_link',
            field=models.CharField(default='', max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='GroupTacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group')),
                ('tack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tack.tack')),
            ],
            options={
                'verbose_name': 'Group Tack',
                'verbose_name_plural': 'Group Tacks',
                'db_table': 'group_tacks',
            },
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group membership',
                'verbose_name_plural': 'Groups membership',
                'db_table': 'group_membership',
            },
        ),
        migrations.CreateModel(
            name='GroupInvitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gi_invitee', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gi_inviter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group invitation',
                'verbose_name_plural': 'Groups invitation',
                'db_table': 'group_invitations',
            },
        ),
    ]
