# Generated by Django 4.0.6 on 2022-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmembers',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='unique_member_for_group'),
        ),
    ]
