# Generated by Django 4.0.7 on 2022-09-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='is_active',
        ),
    ]
