# Generated by Django 4.0.6 on 2022-07-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_groupmembers_unique_member_for_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
    ]
