# Generated by Django 4.1 on 2022-08-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0004_remove_groupinvitations_creation_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembers",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="GroupMutes",
        ),
    ]
