# Generated by Django 4.0.6 on 2022-08-01 08:19

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=group.models.upload_path_group_image),
        ),
    ]
