# Generated by Django 4.0.8 on 2022-10-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_owner_alter_groupinvitations_invitee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='collect_stats',
            field=models.BooleanField(default=False),
        ),
    ]
