# Generated by Django 4.1 on 2022-08-26 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0005_groupmembers_is_muted_delete_groupmutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembers",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
