# Generated by Django 4.0.8 on 2022-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_group_collect_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='collect_stats',
            field=models.BooleanField(default=True),
        ),
    ]
