# Generated by Django 4.1 on 2022-08-28 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0006_groupmembers_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembers",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupmembers",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
