# Generated by Django 4.0.8 on 2022-10-14 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0002_alter_globalstats_avg_amount_per_bank_deposit_w_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstats',
            name='users_visits_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupstats',
            name='users_visits_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='User visits')),
            ],
            options={
                'verbose_name': 'User Visits',
                'verbose_name_plural': 'User Visits',
                'db_table': 'user_visits',
            },
        ),
    ]
