# Generated by Django 4.0.8 on 2022-10-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_uservisits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservisits',
            options={'verbose_name': 'User Visits', 'verbose_name_plural': 'User Visits'},
        ),
        migrations.AddField(
            model_name='globalstats',
            name='users_visits_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupstats',
            name='users_visits_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
