# Generated by Django 4.0.8 on 2022-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_globalstats_users_visits_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalstats',
            name='avg_first_offer_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='globalstats',
            name='avg_tackers_time_estimation',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupstats',
            name='avg_first_offer_time',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupstats',
            name='avg_tackers_time_estimation',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
