# Generated by Django 4.0.8 on 2022-10-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_globalstats_avg_first_offer_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_user_timedelta_days', models.PositiveSmallIntegerField(default=7)),
                ('amount_of_tacks_for_tacker', models.PositiveSmallIntegerField(default=1)),
                ('amount_of_tacks_for_runner', models.PositiveSmallIntegerField(default=3)),
                ('tack_created_last_x_days_for_tacker', models.PositiveSmallIntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Tack Definition',
                'verbose_name_plural': 'Tack Definitions',
                'db_table': 'custom_definitions',
            },
        ),
    ]
