# Generated by Django 4.0.8 on 2022-10-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalstats',
            name='avg_first_offer_time',
        ),
        migrations.RemoveField(
            model_name='groupstats',
            name='avg_first_offer_time',
        ),
    ]
