# Generated by Django 4.0.8 on 2022-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_remove_globalstats_avg_first_offer_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstats',
            name='avg_first_offer_time',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='groupstats',
            name='avg_first_offer_time',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
