# Generated by Django 4.0.8 on 2022-10-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_groupstats_avg_amount_per_bank_deposit_w_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstats',
            name='avg_first_offer_time_seconds',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='groupstats',
            name='avg_first_offer_time_seconds',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
