# Generated by Django 4.0.8 on 2022-11-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_globalstats_avg_first_offer_time_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalstats',
            name='avg_first_offer_time_seconds',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='First Offer Time Seconds'),
        ),
        migrations.AlterField(
            model_name='globalstats',
            name='num_tacks_accepted_last_hour',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Accepted Tacks'),
        ),
        migrations.AlterField(
            model_name='globalstats',
            name='num_tacks_completed_last_hour',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Completed Tacks'),
        ),
        migrations.AlterField(
            model_name='globalstats',
            name='num_tacks_created_last_hour',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Created Tacks'),
        ),
        migrations.AlterField(
            model_name='globalstats',
            name='total_sum_fees_we_paid_last_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupstats',
            name='avg_first_offer_time_seconds',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='First Offer Time Seconds'),
        ),
        migrations.AlterField(
            model_name='groupstats',
            name='num_tacks_accepted_last_hour',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Accepted Tacks'),
        ),
        migrations.AlterField(
            model_name='groupstats',
            name='num_tacks_completed_last_hour',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Completed Tacks'),
        ),
        migrations.AlterField(
            model_name='groupstats',
            name='num_tacks_created_last_hour',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Created Tacks'),
        ),
        migrations.AlterField(
            model_name='groupstats',
            name='total_sum_fees_we_paid_last_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
