# Generated by Django 3.2.13 on 2022-07-04 08:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("sms_code", models.CharField(max_length=6)),
                ("message_sid", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Verification",
                "verbose_name_plural": "Verifications",
                "db_table": "verifications",
            },
        ),
    ]
