# Generated by Django 4.0.6 on 2022-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_phoneverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='sms_type',
            field=models.CharField(choices=[('R', 'Recovery'), ('S', 'Signup')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
