# Generated by Django 4.0.6 on 2022-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
