# Generated by Django 4.0.7 on 2022-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_timeoutsettings_failedloginattempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tack_created', 'Tack created'), ('tack_accepted', 'Tack accepted'), ('tack_in_progress', 'Tack in progress'), ('tack_waiting_review', 'Tack waiting for review'), ('tack_finished', 'Tack finished'), ('tack_expiring', 'Tack expiring'), ('tack_inactive', 'Tack inactive'), ('tack_canceled', 'Tack cancelled'), ('offer_received', 'Offer received'), ('counteroffer_received', 'Counter-offer received'), ('offer_accepted', 'Offer accepted'), ('runner_finished', 'Runner finished'), ('offer_expired', 'Offer expired')], max_length=32)),
                ('title_template', models.TextField(blank=True, max_length=100, null=True)),
                ('body_template', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Notification settings',
                'verbose_name_plural': 'Notification settings',
                'db_table': 'notification_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationsettings',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_type_for_settings'),
        ),
    ]
