# Generated by Django 4.0.6 on 2022-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_phoneverification_sms_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
