# Generated by Django 4.0.7 on 2022-08-08 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_phoneverification_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverification',
            name='created',
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
